config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  registrations: "admin/registrations",
  sessions: "admin/sessions"
  }
  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  
  # Public側
  scope module: :public do
    # Homes
    root to: 'homes#top' # トップページ
    get 'about', to: 'homes#about'

    # Users
    get 'mypage', to: 'users#mypage'
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        post 'follow'
        delete 'unfollow'
        get 'followers'
        get 'followings'
      end
    end

    # Posts
    resources :posts do
      collection do
        get 'likes', to: 'posts#like_index'
      end
      resource :like, only: [:create, :destroy] # 投稿ごとのいいね
      resources :comments, only: [:create, :destroy] do # 投稿に対するコメント
        resource :like, only: [:create, :destroy] # 投稿のコメントに対するいいね
      end
    end

    # Tickets
    get 'tickets/users/:id', to: 'tickets#my_tickets', as: 'user_tickets' # 自分の所持しているチケット一覧
    get 'tickets/issued_tickets/:user_id', to: 'tickets#issued_tickets', as: 'user_issued_tickets' # ユーザーの発行したチケット一覧。パスの最後はユーザーIDを受け取る。
    get 'tickets/:id/individual_tickets', to: 'tickets#individual_tickets', as: 'issued_individual_tickets'# ユーザーの発行したチケットの個別チケット一覧。
    resources :tickets do
      resource :like, only: [:create, :destroy] # チケットごとのいいね
      resources :comments, only: [:create, :destroy] do # チケットに対するコメント
        resource :like, only: [:create, :destroy] # チケットのコメントに対するいいね
      end
    end
    
    # IndividualTickets
    resources :individual_tickets, only: [:index, :show, :update] do
      collection do
        post :acquire # チケットを取得する
      end
      
      member do
        get :transfer # チケット譲渡用（ビュー表示）
        patch :transferred # チケット譲渡用（更新）
        patch :mark_as_used # チケットを使用済みにする
      end
    end
    
    # Requests
    resources :requests, only: [:create, :update]
    
    # Notifications
    resources :notifications, only: [:index, :show, :destroy]

    # Likes
    get 'users/:id/likes/posts', to: 'likes#index_posts', as: 'user_post_likes'
    get 'users/:id/likes/tickets', to: 'likes#index_tickets', as: 'user_ticket_likes'


    # Relationships (follows/unfollows)
    resources :relationships, only: [:create, :destroy]
  end

  # Adminネームスペース
  namespace :admin do
    # Admin Users
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get 'followers'
        get 'followings'
      end
    end

    # Admin notifications
    resources :admin_notifications, only: [:new, :create, :index]
  end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Takki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/0e44a172cd.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
     <nav class="navbar navbar-expand-lg navbar-light">
      
      <div class="container">
       
       <% if admin_signed_in? %>
        <%= link_to admin_path, class: "navbar-brand p-3" do %>
         <p>Takki</p>
        <% end %>
       <% else %>
        <%= link_to root_path, class: "navbar-brand p-3" do %>
         <p>Takki</p>
        <% end %>
       <% end %>
       
       <button class="navbar-toggler btn btn-light" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
       </button>
      
       <div class="d-flex justify-content-end collapse navbar-collapse" id="navbarNavDropdown">
        
        <% if user_signed_in? %>
         
         <p class="mx-5">ようこそ、<%= current_user.name %>さん!</p>
         
         <ul class = "navbar-nav ml-auto p-2" >
           <li class="nav-item">
            <%= link_to mypage_path, class:"btn btn-light" do %>
             <p>マイページ</p>
            <% end %>
           </li>
           
           <li class="nav-item">
            <%= link_to users_path, class:"btn btn-light" do %>
             <p>ユーザー一覧</p>
            <% end %>
           </li>
           
           <li class="nav-item mx-2">
            <%= link_to new_post_path,class:"btn btn-light" do %>
             <p>新規投稿</p>
            <% end %>
           </li>
           
           <li class="nav-item mx-2">
            <%= link_to new_ticket_path,class:"btn btn-light" do %>
             <p>新規チケット作成</p>
            <% end %>
           </li>
           
           <li class="nav-item mx-2">
            <%= link_to posts_path,class:"btn btn-light" do %>
             <p>投稿一覧</p>
            <% end %>
           </li>
           
           <li class="nav-item mx-2">
            <%= link_to tickets_path,class:"btn btn-light" do %>
             <p>チケット一覧</p>
            <% end %>
           </li>
          
          <li class="nav-item mx-2">
            <%= link_to notifications_path, class:"btn btn-light" do %>
             <p>通知一覧</p>
            <% end %>
           </li>
           
           
           <li class="nav-item mx-2">
            <%= link_to destroy_user_session_path, method: :delete,class:"btn btn-light" do %>
             <p>ログアウト</p>
            <% end %>
           </li>
         </ul>
        <% elsif admin_signed_in? %>
         <ul class="navbar-nav ml-auto p-2">
           <li class="nav-item mx-2">
            <%= link_to tickets_path,class:"btn btn-light" do %>
             <p>チケット一覧</p>
            <% end %>
           </li>
           
           <li class="nav-item mx-2">
            <%= link_to admin_users_path,class:"btn btn-light" do %>
             <p>ユーザー一覧</p>
            <% end %>
           </li>
           
           <li class="nav-item mx-2">
            <%= link_to posts_path,class:"btn btn-light" do %>
             <p>投稿一覧</p>
            <% end %>
           </li>
           
           
           <li class="nav-item mx-2">
            <%= link_to destroy_admin_session_path, method: :delete,class:"btn btn-light" do %>
             <p>ログアウト</p>
            <% end %>
           </li>
         </ul>
         
        <% else %>
         <ul class="navbar-nav ml-auto p-2">
           
           <li class="nav-item mx-2">
            <%= link_to tickets_path,class:"btn btn-light" do %>
             <p class="align-middle">チケット一覧</p>
            <% end %>
           </li>
           
           <li class="nav-item mx-2">
            <%= link_to posts_path,class:"btn btn-light" do %>
             <p>投稿一覧</p>
            <% end %>
           </li>
           
           <li class="nav-item mx-2">
            <%= link_to new_user_registration_path,class:"btn btn-light" do %>
             <p>新規登録</p>
            <% end %>
           </li>
           <li class="nav-item mx-2">
            <%= link_to new_user_session_path,class:"btn btn-light" do %>
             <p>ログイン</p>
            <% end %>
           </li>
         </ul>
        <% end %>
        
       </div> <!-- collaps終了 -->
       
      </div><!-- containar class終了 -->
     </nav><!-- nav終了 -->
      
    </header>
    
    <main>
     <div class="container my-5 px-5 px-sm-0">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
     </div>
    </main>
    
    <footer class="bg-light text-white pt-5 pb-4">
     
    </footer>
    
    
  </body>
</html>